// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateInterestRecord(ctx context.Context, arg CreateInterestRecordParams) error
	CreateNewPost(ctx context.Context, arg CreateNewPostParams) (PostInfo, error)
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) (UsersInfo, error)
	CreateTradingRecord(ctx context.Context, arg CreateTradingRecordParams) (TradingHistory, error)
	DeleteInterestRecord(ctx context.Context, arg DeleteInterestRecordParams) error
	DeletePost(ctx context.Context, id int64) error
	DeleteTradingRecord(ctx context.Context, arg DeleteTradingRecordParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetPost(ctx context.Context, id int64) (PostInfo, error)
	GetPostAndRelatedUser(ctx context.Context, id int64) (GetPostAndRelatedUserRow, error)
	GetPostInterestList(ctx context.Context, postID int64) ([]GetPostInterestListRow, error)
	GetPostList(ctx context.Context, arg GetPostListParams) ([]PostInfo, error)
	GetRecord(ctx context.Context, id int64) (TradingHistory, error)
	GetRecordList(ctx context.Context, arg GetRecordListParams) ([]TradingHistory, error)
	GetUser(ctx context.Context, id int64) (UsersInfo, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (PostInfo, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (UsersInfo, error)
}

var _ Querier = (*Queries)(nil)
