// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateInterestRecord(ctx context.Context, arg CreateInterestRecordParams) error
	CreateNewPost(ctx context.Context, arg CreateNewPostParams) (PostInfo, error)
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) (UsersInfo, error)
	CreateTradingRecord(ctx context.Context, arg CreateTradingRecordParams) (TradingHistory, error)
	DeleteInterestRecord(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, id int64) error
	DeleteTradingRecord(ctx context.Context, arg DeleteTradingRecordParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetInterestListByUserID(ctx context.Context, interestedUserID int64) ([]GetInterestListByUserIDRow, error)
	GetInterestRecordByUserIdAndPostId(ctx context.Context, arg GetInterestRecordByUserIdAndPostIdParams) (int64, error)
	GetMyPostList(ctx context.Context, postUserID int64) ([]PostInfo, error)
	GetPost(ctx context.Context, id int64) (PostInfo, error)
	GetPostAndRelatedUser(ctx context.Context, id int64) (GetPostAndRelatedUserRow, error)
	GetPostInterestList(ctx context.Context, postID int64) ([]GetPostInterestListRow, error)
	GetPostListAuth(ctx context.Context, arg GetPostListAuthParams) ([]GetPostListAuthRow, error)
	GetPostListNoAuth(ctx context.Context, arg GetPostListNoAuthParams) ([]PostInfo, error)
	GetPurchaseByUserId(ctx context.Context, soldToUserID int64) ([]GetPurchaseByUserIdRow, error)
	GetRecord(ctx context.Context, id int64) (TradingHistory, error)
	GetRecordList(ctx context.Context, arg GetRecordListParams) ([]TradingHistory, error)
	GetUserByEmail(ctx context.Context, email string) (UsersInfo, error)
	GetUserById(ctx context.Context, id int64) (UsersInfo, error)
	SoldPost(ctx context.Context, id int64) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (PostInfo, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (UsersInfo, error)
}

var _ Querier = (*Queries)(nil)
